// generated by SMACK version 2.6.3 for corral
// via /usr/local/bin/smack ../testcases/svcomp/memsafety/test-0232-2.c -ll ../testcases/svcomp/memsafety/test-0232-2_IR.ll --bpl ../testcases/svcomp/memsafety/test-0232-2.bpl -t --sh-mem-leak --add-line-info

const main: ref;
axiom (main == $sub.ref(0, 1032));
procedure {:entrypoint} main()
  returns ($r: i32)
{
  var $p0: ref;
  var $i1: i32;
  var $i2: i1;
  var $p3: ref;
  var $i4: i1;
  var $p5: ref;
  var $p6: ref;
  var $p7: ref;
  var $p8: ref;
  var $p9: ref;
  var $p10: ref;
  var $p11: ref8;
  var $p12: ref;
  var $p13: ref8;
  var $p14: ref;
  var $i15: i1;
  var $p16: ref;
  var $p17: ref;
  var $p18: ref;
  var $p19: ref;
  var $p20: ref8;
  var $p21: ref;
  var $i22: i1;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 29, 18} true;
  call {:cexpr "smack:entry:main"} boogie_si_record_ref(main);
  call $p0 := $alloc($mul.ref(8, $zext.i32.i64(1)));
  assume true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 29, 18} true;
  $M.0 := $store.ref($M.0, $p0, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 32, 5} true;
  goto $bb1;
$bb1:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 33, 9} true;
  call append($p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 33, 9} true;
  goto $bb2;
$bb2:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 34, 12} true;
  call $i1 := __VERIFIER_nondet_int();
  call {:cexpr "smack:ext:__VERIFIER_nondet_int"} boogie_si_record_i32($i1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 33, 9} true;
  $i2 := $ne.i32($i1, 0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 33, 9} true;
  assume {:branchcond $i2} true;
  goto $bb3, $bb4;
$bb3:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 33, 9} true;
  assume ($i2 == 1);
  goto $bb1;
$bb4:
  assume !(($i2 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 37, 9} true;
  $p3 := $load.ref($M.0, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 37, 9} true;
  $i4 := $ne.ref($p3, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 37, 9} true;
  assume {:branchcond $i4} true;
  goto $bb5, $bb6;
$bb5:
  assume ($i4 == 1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 38, 29} true;
  $p5 := $load.ref($M.0, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 38, 35} true;
  $p6 := $add.ref($add.ref($p5, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 38, 35} true;
  $p7 := $load.ref($M.1, $p6);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 41, 14} true;
  $p8 := $load.ref($M.0, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 41, 20} true;
  $p9 := $add.ref($add.ref($p8, $mul.ref(0, 16)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 41, 20} true;
  $p10 := $load.ref($M.2, $p9);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 41, 14} true;
  $p11 := $bitcast.ref.ref($p10);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 41, 9} true;
  call free_($p11);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 43, 14} true;
  $p12 := $load.ref($M.0, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 43, 14} true;
  $p13 := $bitcast.ref.ref($p12);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 43, 9} true;
  call free_($p13);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 44, 14} true;
  $M.0 := $store.ref($M.0, $p0, $p7);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 45, 5} true;
  goto $bb7;
$bb6:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 37, 9} true;
  assume !(($i4 == 1));
  goto $bb7;
$bb7:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 49, 12} true;
  $p14 := $load.ref($M.0, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 49, 5} true;
  $i15 := $ne.ref($p14, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 49, 5} true;
  assume {:branchcond $i15} true;
  goto $bb8, $bb9;
$bb8:
  assume ($i15 == 1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 49, 5} true;
  goto $bb11;
$bb9:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 49, 5} true;
  assume !(($i15 == 1));
  goto $bb10;
$bb10:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 55, 5} true;
  $r := 0;
  return;
$bb11:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 50, 29} true;
  $p16 := $load.ref($M.0, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 50, 35} true;
  $p17 := $add.ref($add.ref($p16, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 50, 35} true;
  $p18 := $load.ref($M.1, $p17);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 51, 14} true;
  $p19 := $load.ref($M.0, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 51, 14} true;
  $p20 := $bitcast.ref.ref($p19);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 51, 9} true;
  call free_($p20);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 52, 14} true;
  $M.0 := $store.ref($M.0, $p0, $p18);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 49, 12} true;
  $p21 := $load.ref($M.0, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 49, 5} true;
  $i22 := $ne.ref($p21, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 49, 5} true;
  assume {:branchcond $i22} true;
  goto $bb12, $bb13;
$bb12:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 49, 5} true;
  assume ($i22 == 1);
  goto $bb11;
$bb13:
  assume !(($i22 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 49, 5} true;
  goto $bb10;
}
const llvm.dbg.declare: ref;
axiom (llvm.dbg.declare == $sub.ref(0, 2064));
procedure  llvm.dbg.declare($p0: ref, $p1: ref, $p2: ref);
const append: ref;
axiom (append == $sub.ref(0, 3096));
procedure  append($p0: ref)
{
  var $p1: ref8;
  var $p2: ref;
  var $p3: ref;
  var $p4: ref;
  var $p5: ref;
  var $p6: ref;
  var $i7: i1;
  var $p8: ref;
  var $p9: ref;
  var $p10: ref;
  var $p11: ref;
  var $p12: ref8;
  var $p14: ref8;
  var $p13: ref8;
  var $p15: ref;
  var $p16: ref;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 16, 25} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 16, 25} true;
  call $p1 := malloc(16);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 16, 25} true;
  $p2 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 17, 18} true;
  $p3 := $load.ref($M.0, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 17, 11} true;
  $p4 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 17, 16} true;
  $M.1 := $store.ref($M.1, $p4, $p3);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 20, 25} true;
  $p5 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 20, 25} true;
  $p6 := $load.ref($M.1, $p5);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 20, 18} true;
  $i7 := $ne.ref($p6, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 20, 18} true;
  assume {:branchcond $i7} true;
  goto $bb1, $bb2;
$bb1:
  assume ($i7 == 1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 21, 17} true;
  $p8 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 21, 17} true;
  $p9 := $load.ref($M.1, $p8);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 21, 23} true;
  $p10 := $add.ref($add.ref($p9, $mul.ref(0, 16)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 21, 23} true;
  $p11 := $load.ref($M.2, $p10);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 21, 11} true;
  $p12 := $bitcast.ref.ref($p11);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 20, 18} true;
  $p13 := $p11;
  goto $bb3;
$bb2:
  assume !(($i7 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 22, 11} true;
  call $p14 := malloc(16);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 20, 18} true;
  $p13 := $p14;
  goto $bb3;
$bb3:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 20, 18} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 20, 18} true;
  $p15 := $bitcast.ref.ref($p13);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 20, 11} true;
  $p16 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 20, 16} true;
  $M.2 := $store.ref($M.2, $p16, $p13);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 24, 12} true;
  $M.0 := $store.ref($M.0, $p0, $p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0232-2.c", 25, 1} true;
  return;
}
const __VERIFIER_nondet_int: ref;
axiom (__VERIFIER_nondet_int == $sub.ref(0, 4128));
procedure  __VERIFIER_nondet_int()
  returns ($r: i32);
const free_: ref;
axiom (free_ == $sub.ref(0, 5160));
procedure  free_($p0: ref)
{
  call $free($p0);
}
const malloc: ref;
axiom (malloc == $sub.ref(0, 6192));
procedure  malloc($i0: i64)
  returns ($r: ref)
{
  call $r := $malloc($i0);
}
const llvm.dbg.value: ref;
axiom (llvm.dbg.value == $sub.ref(0, 7224));
procedure  llvm.dbg.value($p0: ref, $p1: ref, $p2: ref);
const __SMACK_static_init: ref;
axiom (__SMACK_static_init == $sub.ref(0, 8256));
procedure  __SMACK_static_init()
{
$bb0:
  return;
}
procedure  boogie_si_record_i32(x: i32);
procedure  boogie_si_record_ref(x: ref);
procedure  $initialize()
{
  call __SMACK_static_init();
  return;
}
