// generated by SMACK version 2.6.3 for corral
// via /usr/local/bin/smack ../testcases/svcomp/memsafety/test-0237.i -ll ../testcases/svcomp/memsafety/test-0237_IR.ll --bpl ../testcases/svcomp/memsafety/test-0237.bpl -t --sh-mem-leak --add-line-info

const {:global_variable} {:pointer_to_size 16} .str: ref;
axiom (.str == $sub.ref(0, 1026));
const {:global_variable} {:pointer_to_size 96} {:count 12} .str.1: ref;
axiom (.str.1 == $sub.ref(0, 2062));
const {:global_variable} {:pointer_to_size 152} {:count 19} __PRETTY_FUNCTION__.reach_error: ref;
axiom (__PRETTY_FUNCTION__.reach_error == $sub.ref(0, 3105));
const {:global_variable} {:pointer_to_size 64} main.list: ref;
axiom (main.list == $sub.ref(0, 4137));
const reach_error: ref;
axiom (reach_error == $sub.ref(0, 5169));
procedure  reach_error()
{
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 12, 83} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 12, 83} true;
  call __assert_fail(.str, .str.1, 3, __PRETTY_FUNCTION__.reach_error);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 12, 83} true;
  assume false;
}
const __assert_fail: ref;
axiom (__assert_fail == $sub.ref(0, 6201));
procedure  __assert_fail($p0: ref, $p1: ref, $i2: i32, $p3: ref);
const main: ref;
axiom (main == $sub.ref(0, 7233));
procedure {:entrypoint} main()
  returns ($r: i32)
{
  var $i0: i32;
  var $i1: i1;
  var $p2: ref;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 777, 5} true;
  call {:cexpr "smack:entry:main"} boogie_si_record_ref(main);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 777, 5} true;
  goto $bb1;
$bb1:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 778, 9} true;
  call l0_insert(main.list);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 778, 9} true;
  goto $bb2;
$bb2:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 779, 12} true;
  call $i0 := __VERIFIER_nondet_int();
  call {:cexpr "smack:ext:__VERIFIER_nondet_int"} boogie_si_record_i32($i0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 778, 9} true;
  $i1 := $ne.i32($i0, 0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 778, 9} true;
  assume {:branchcond $i1} true;
  goto $bb3, $bb4;
$bb3:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 778, 9} true;
  assume ($i1 == 1);
  goto $bb1;
$bb4:
  assume !(($i1 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 780, 16} true;
  $p2 := $load.ref($M.0, main.list);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 780, 5} true;
  call l0_destroy($p2);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 781, 1} true;
  $r := 0;
  return;
}
const l0_insert: ref;
axiom (l0_insert == $sub.ref(0, 8265));
procedure  l0_insert($p0: ref)
{
  var $p1: ref8;
  var $p2: ref;
  var $p3: ref;
  var $i4: i32;
  var $i5: i1;
  var $p6: ref;
  var $p7: ref;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 717, 23} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 717, 23} true;
  call $p1 := zalloc_or_die(16);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 717, 23} true;
  $p2 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 718, 5} true;
  goto $bb1;
$bb1:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 719, 26} true;
  $p3 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 719, 9} true;
  call l1_insert($p3);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 719, 9} true;
  goto $bb2;
$bb2:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 720, 12} true;
  call $i4 := __VERIFIER_nondet_int();
  call {:cexpr "smack:ext:__VERIFIER_nondet_int"} boogie_si_record_i32($i4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 719, 9} true;
  $i5 := $ne.i32($i4, 0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 719, 9} true;
  assume {:branchcond $i5} true;
  goto $bb3, $bb4;
$bb3:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 719, 9} true;
  assume ($i5 == 1);
  goto $bb1;
$bb4:
  assume !(($i5 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 721, 18} true;
  $p6 := $load.ref($M.0, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 721, 11} true;
  $p7 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 721, 16} true;
  $M.1 := $store.ref($M.1, $p7, $p6);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 722, 11} true;
  $M.0 := $store.ref($M.0, $p0, $p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 723, 1} true;
  return;
}
const __VERIFIER_nondet_int: ref;
axiom (__VERIFIER_nondet_int == $sub.ref(0, 9297));
procedure  __VERIFIER_nondet_int()
  returns ($r: i32);
const l0_destroy: ref;
axiom (l0_destroy == $sub.ref(0, 10329));
procedure  l0_destroy($p0: ref)
{
  var $p1: ref;
  var $p2: ref;
  var $p3: ref;
  var $p4: ref;
  var $p5: ref;
  var $p6: ref8;
  var $i7: i1;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 766, 5} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 766, 5} true;
  $p1 := $p0;
  goto $bb1;
$bb1:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 767, 26} true;
  $p2 := $add.ref($add.ref($p1, $mul.ref(0, 16)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 767, 26} true;
  $p3 := $load.ref($M.1, $p2);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 767, 9} true;
  call l1_destroy($p3);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 768, 33} true;
  $p4 := $add.ref($add.ref($p1, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 768, 33} true;
  $p5 := $load.ref($M.1, $p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 769, 14} true;
  $p6 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 769, 9} true;
  call free_($p6);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 771, 5} true;
  goto $bb2;
$bb2:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 771, 5} true;
  $i7 := $ne.ref($p5, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 771, 5} true;
  assume {:branchcond $i7} true;
  goto $bb3, $bb4;
$bb3:
  assume ($i7 == 1);
  $p1 := $p5;
  goto $bb1;
$bb4:
  assume !(($i7 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 773, 1} true;
  return;
}
const llvm.dbg.declare: ref;
axiom (llvm.dbg.declare == $sub.ref(0, 11361));
procedure  llvm.dbg.declare($p0: ref, $p1: ref, $p2: ref);
const l1_destroy: ref;
axiom (l1_destroy == $sub.ref(0, 12393));
procedure  l1_destroy($p0: ref)
{
  var $p1: ref;
  var $p2: ref;
  var $p3: ref;
  var $p4: ref;
  var $p5: ref;
  var $p6: ref8;
  var $i7: i1;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 756, 5} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 756, 5} true;
  $p1 := $p0;
  goto $bb1;
$bb1:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 757, 26} true;
  $p2 := $add.ref($add.ref($p1, $mul.ref(0, 24)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 757, 26} true;
  $p3 := $load.ref($M.1, $p2);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 757, 9} true;
  call l2_destroy($p3);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 758, 33} true;
  $p4 := $add.ref($add.ref($p1, $mul.ref(0, 24)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 758, 33} true;
  $p5 := $load.ref($M.1, $p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 759, 14} true;
  $p6 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 759, 9} true;
  call free_($p6);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 761, 5} true;
  goto $bb2;
$bb2:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 761, 5} true;
  $i7 := $ne.ref($p5, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 761, 5} true;
  assume {:branchcond $i7} true;
  goto $bb3, $bb4;
$bb3:
  assume ($i7 == 1);
  $p1 := $p5;
  goto $bb1;
$bb4:
  assume !(($i7 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 763, 1} true;
  return;
}
const free_: ref;
axiom (free_ == $sub.ref(0, 13425));
procedure  free_($p0: ref)
{
  call $free($p0);
}
const l2_destroy: ref;
axiom (l2_destroy == $sub.ref(0, 14457));
procedure  l2_destroy($p0: ref)
{
  var $p1: ref;
  var $p2: ref;
  var $p3: ref;
  var $p4: ref;
  var $p5: ref;
  var $p6: ref8;
  var $i7: i1;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 746, 5} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 746, 5} true;
  $p1 := $p0;
  goto $bb1;
$bb1:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 747, 26} true;
  $p2 := $add.ref($add.ref($p1, $mul.ref(0, 24)), $mul.ref(16, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 747, 26} true;
  $p3 := $load.ref($M.1, $p2);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 747, 9} true;
  call l3_destroy($p3);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 748, 33} true;
  $p4 := $add.ref($add.ref($p1, $mul.ref(0, 24)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 748, 33} true;
  $p5 := $load.ref($M.1, $p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 749, 14} true;
  $p6 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 749, 9} true;
  call free_($p6);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 751, 5} true;
  goto $bb2;
$bb2:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 751, 5} true;
  $i7 := $ne.ref($p5, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 751, 5} true;
  assume {:branchcond $i7} true;
  goto $bb3, $bb4;
$bb3:
  assume ($i7 == 1);
  $p1 := $p5;
  goto $bb1;
$bb4:
  assume !(($i7 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 753, 1} true;
  return;
}
const l3_destroy: ref;
axiom (l3_destroy == $sub.ref(0, 15489));
procedure  l3_destroy($p0: ref)
{
  var $p1: ref;
  var $p2: ref;
  var $p3: ref;
  var $p4: ref;
  var $p5: ref;
  var $p6: ref8;
  var $i7: i1;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 736, 5} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 736, 5} true;
  $p1 := $p0;
  goto $bb1;
$bb1:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 737, 26} true;
  $p2 := $add.ref($add.ref($p1, $mul.ref(0, 24)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 737, 26} true;
  $p3 := $load.ref($M.1, $p2);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 737, 9} true;
  call l4_destroy($p3);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 738, 33} true;
  $p4 := $add.ref($add.ref($p1, $mul.ref(0, 24)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 738, 33} true;
  $p5 := $load.ref($M.1, $p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 739, 14} true;
  $p6 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 739, 9} true;
  call free_($p6);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 741, 5} true;
  goto $bb2;
$bb2:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 741, 5} true;
  $i7 := $ne.ref($p5, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 741, 5} true;
  assume {:branchcond $i7} true;
  goto $bb3, $bb4;
$bb3:
  assume ($i7 == 1);
  $p1 := $p5;
  goto $bb1;
$bb4:
  assume !(($i7 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 743, 1} true;
  return;
}
const l4_destroy: ref;
axiom (l4_destroy == $sub.ref(0, 16521));
procedure  l4_destroy($p0: ref)
{
  var $p1: ref;
  var $p2: ref;
  var $p3: ref;
  var $p4: ref8;
  var $p5: ref;
  var $p6: ref;
  var $p7: ref8;
  var $i8: i1;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 726, 5} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 726, 5} true;
  $p1 := $p0;
  goto $bb1;
$bb1:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 727, 20} true;
  $p2 := $add.ref($add.ref($p1, $mul.ref(0, 24)), $mul.ref(16, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 727, 20} true;
  $p3 := $load.ref($M.1, $p2);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 727, 14} true;
  $p4 := $bitcast.ref.ref($p3);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 727, 9} true;
  call free_($p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 728, 33} true;
  $p5 := $add.ref($add.ref($p1, $mul.ref(0, 24)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 728, 33} true;
  $p6 := $load.ref($M.1, $p5);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 729, 14} true;
  $p7 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 729, 9} true;
  call free_($p7);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 731, 5} true;
  goto $bb2;
$bb2:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 731, 5} true;
  $i8 := $ne.ref($p6, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 731, 5} true;
  assume {:branchcond $i8} true;
  goto $bb3, $bb4;
$bb3:
  assume ($i8 == 1);
  $p1 := $p6;
  goto $bb1;
$bb4:
  assume !(($i8 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 733, 1} true;
  return;
}
const zalloc_or_die: ref;
axiom (zalloc_or_die == $sub.ref(0, 17553));
procedure  zalloc_or_die($i0: i32)
  returns ($r: ref)
{
  var $p1: ref8;
  var $i2: i1;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 671, 17} true;
  call {:cexpr "zalloc_or_die:arg:size"} boogie_si_record_i32($i0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 671, 17} true;
  call $p1 := calloc_model(1, $i0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 672, 9} true;
  $i2 := $ne.ref($p1, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 672, 9} true;
  assume {:branchcond $i2} true;
  goto $bb1, $bb2;
$bb1:
  assume ($i2 == 1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 673, 9} true;
  $r := $p1;
  return;
$bb2:
  assume !(($i2 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 674, 5} true;
  call abort();
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 674, 5} true;
  assume false;
}
const l1_insert: ref;
axiom (l1_insert == $sub.ref(0, 18585));
procedure  l1_insert($p0: ref)
{
  var $p1: ref8;
  var $p2: ref;
  var $p3: ref;
  var $p4: ref8;
  var $i5: i32;
  var $i6: i1;
  var $p7: ref;
  var $p8: ref;
  var $p9: ref;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 707, 23} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 707, 23} true;
  call $p1 := zalloc_or_die(24);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 707, 23} true;
  $p2 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 708, 5} true;
  goto $bb1;
$bb1:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 709, 26} true;
  $p3 := $add.ref($add.ref($p2, $mul.ref(0, 24)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 709, 32} true;
  $p4 := $bitcast.ref.ref($p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 709, 9} true;
  call l2_insert($p3, $p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 709, 9} true;
  goto $bb2;
$bb2:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 710, 12} true;
  call $i5 := __VERIFIER_nondet_int();
  call {:cexpr "smack:ext:__VERIFIER_nondet_int"} boogie_si_record_i32($i5);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 709, 9} true;
  $i6 := $ne.i32($i5, 0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 709, 9} true;
  assume {:branchcond $i6} true;
  goto $bb3, $bb4;
$bb3:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 709, 9} true;
  assume ($i6 == 1);
  goto $bb1;
$bb4:
  assume !(($i6 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 711, 11} true;
  $p7 := $add.ref($add.ref($p2, $mul.ref(0, 24)), $mul.ref(16, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 711, 17} true;
  $M.1 := $store.ref($M.1, $p7, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 712, 18} true;
  $p8 := $load.ref($M.1, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 712, 11} true;
  $p9 := $add.ref($add.ref($p2, $mul.ref(0, 24)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 712, 16} true;
  $M.1 := $store.ref($M.1, $p9, $p8);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 713, 11} true;
  $M.1 := $store.ref($M.1, $p0, $p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 714, 1} true;
  return;
}
const l2_insert: ref;
axiom (l2_insert == $sub.ref(0, 19617));
procedure  l2_insert($p0: ref, $p1: ref)
{
  var $p2: ref8;
  var $p3: ref;
  var $p4: ref;
  var $i5: i32;
  var $i6: i1;
  var $p7: ref;
  var $p8: ref;
  var $p9: ref;
  var $p10: ref;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 697, 23} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 697, 23} true;
  call $p2 := zalloc_or_die(24);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 697, 23} true;
  $p3 := $bitcast.ref.ref($p2);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 698, 5} true;
  goto $bb1;
$bb1:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 699, 26} true;
  $p4 := $add.ref($add.ref($p3, $mul.ref(0, 24)), $mul.ref(16, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 699, 9} true;
  call l3_insert($p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 699, 9} true;
  goto $bb2;
$bb2:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 700, 12} true;
  call $i5 := __VERIFIER_nondet_int();
  call {:cexpr "smack:ext:__VERIFIER_nondet_int"} boogie_si_record_i32($i5);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 699, 9} true;
  $i6 := $ne.i32($i5, 0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 699, 9} true;
  assume {:branchcond $i6} true;
  goto $bb3, $bb4;
$bb3:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 699, 9} true;
  assume ($i6 == 1);
  goto $bb1;
$bb4:
  assume !(($i6 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 701, 19} true;
  $p7 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 701, 11} true;
  $p8 := $add.ref($add.ref($p3, $mul.ref(0, 24)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 701, 17} true;
  $M.1 := $store.ref($M.1, $p8, $p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 702, 18} true;
  $p9 := $load.ref($M.1, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 702, 11} true;
  $p10 := $add.ref($add.ref($p3, $mul.ref(0, 24)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 702, 16} true;
  $M.1 := $store.ref($M.1, $p10, $p9);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 703, 11} true;
  $M.1 := $store.ref($M.1, $p0, $p2);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 704, 1} true;
  return;
}
const l3_insert: ref;
axiom (l3_insert == $sub.ref(0, 20649));
procedure  l3_insert($p0: ref)
{
  var $p1: ref8;
  var $p2: ref;
  var $p3: ref;
  var $p4: ref8;
  var $i5: i32;
  var $i6: i1;
  var $p7: ref;
  var $p8: ref;
  var $p9: ref;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 687, 23} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 687, 23} true;
  call $p1 := zalloc_or_die(24);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 687, 23} true;
  $p2 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 688, 5} true;
  goto $bb1;
$bb1:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 689, 26} true;
  $p3 := $add.ref($add.ref($p2, $mul.ref(0, 24)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 689, 32} true;
  $p4 := $bitcast.ref.ref($p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 689, 9} true;
  call l4_insert($p3, $p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 689, 9} true;
  goto $bb2;
$bb2:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 690, 12} true;
  call $i5 := __VERIFIER_nondet_int();
  call {:cexpr "smack:ext:__VERIFIER_nondet_int"} boogie_si_record_i32($i5);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 689, 9} true;
  $i6 := $ne.i32($i5, 0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 689, 9} true;
  assume {:branchcond $i6} true;
  goto $bb3, $bb4;
$bb3:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 689, 9} true;
  assume ($i6 == 1);
  goto $bb1;
$bb4:
  assume !(($i6 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 691, 11} true;
  $p7 := $add.ref($add.ref($p2, $mul.ref(0, 24)), $mul.ref(16, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 691, 17} true;
  $M.1 := $store.ref($M.1, $p7, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 692, 18} true;
  $p8 := $load.ref($M.1, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 692, 11} true;
  $p9 := $add.ref($add.ref($p2, $mul.ref(0, 24)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 692, 16} true;
  $M.1 := $store.ref($M.1, $p9, $p8);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 693, 11} true;
  $M.1 := $store.ref($M.1, $p0, $p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 694, 1} true;
  return;
}
const l4_insert: ref;
axiom (l4_insert == $sub.ref(0, 21681));
procedure  l4_insert($p0: ref, $p1: ref)
{
  var $p2: ref8;
  var $p3: ref;
  var $p4: ref8;
  var $p5: ref;
  var $p6: ref;
  var $p7: ref8;
  var $p8: ref;
  var $p9: ref;
  var $p10: ref;
  var $p11: ref;
  var $p12: ref;
  var $p13: ref;
  var $p14: ref;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 678, 23} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 678, 23} true;
  call $p2 := zalloc_or_die(24);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 678, 23} true;
  $p3 := $bitcast.ref.ref($p2);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 679, 18} true;
  call $p4 := zalloc_or_die(119);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 679, 18} true;
  $p5 := $bitcast.ref.ref($p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 679, 11} true;
  $p6 := $add.ref($add.ref($p3, $mul.ref(0, 24)), $mul.ref(16, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 679, 16} true;
  $M.1 := $store.ref($M.1, $p6, $p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 680, 30} true;
  $p7 := $bitcast.ref.ref($p3);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 680, 22} true;
  $p8 := $add.ref($add.ref($p3, $mul.ref(0, 24)), $mul.ref(16, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 680, 22} true;
  $p9 := $load.ref($M.1, $p8);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 680, 5} true;
  $p10 := $bitcast.ref.ref($p9);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 680, 28} true;
  $M.1 := $store.ref($M.1, $p10, $p2);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 681, 19} true;
  $p11 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 681, 11} true;
  $p12 := $add.ref($add.ref($p3, $mul.ref(0, 24)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 681, 17} true;
  $M.1 := $store.ref($M.1, $p12, $p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 682, 18} true;
  $p13 := $load.ref($M.1, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 682, 11} true;
  $p14 := $add.ref($add.ref($p3, $mul.ref(0, 24)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 682, 16} true;
  $M.1 := $store.ref($M.1, $p14, $p13);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 683, 11} true;
  $M.1 := $store.ref($M.1, $p0, $p2);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 684, 1} true;
  return;
}
const calloc_model: ref;
axiom (calloc_model == $sub.ref(0, 22713));
procedure  calloc_model($i0: i32, $i1: i32)
  returns ($r: ref)
{
  var $i2: i32;
  var $p3: ref8;
  var $i4: i32;
  var $p5: ref8;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 641, 30} true;
  call {:cexpr "calloc_model:arg:nmemb"} boogie_si_record_i32($i0);
  call {:cexpr "calloc_model:arg:size"} boogie_si_record_i32($i1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 641, 30} true;
  $i2 := $mul.i32($i0, $i1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 641, 17} true;
  call $p3 := malloc($i2);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 642, 33} true;
  $i4 := $mul.i32($i0, $i1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 642, 12} true;
  call $p5 := memset($p3, 0, $i4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0237.i", 642, 5} true;
  $r := $p5;
  return;
}
const abort: ref;
axiom (abort == $sub.ref(0, 23745));
procedure  abort();
const malloc: ref;
axiom (malloc == $sub.ref(0, 24777));
procedure  malloc($i0: i32)
  returns ($r: ref)
{
  call $r := $malloc($zext.i32.i64($i0));
}
const memset: ref;
axiom (memset == $sub.ref(0, 25809));
procedure  memset($p0: ref, $i1: i32, $i2: i32)
  returns ($r: ref);
const llvm.dbg.value: ref;
axiom (llvm.dbg.value == $sub.ref(0, 26841));
procedure  llvm.dbg.value($p0: ref, $p1: ref, $p2: ref);
const __SMACK_static_init: ref;
axiom (__SMACK_static_init == $sub.ref(0, 27873));
procedure  __SMACK_static_init()
{
$bb0:
  $M.0 := $store.ref($M.0, main.list, $0.ref);
  return;
}
procedure  boogie_si_record_i32(x: i32);
procedure  boogie_si_record_ref(x: ref);
procedure  $initialize()
{
  call __SMACK_static_init();
  return;
}
