// generated by SMACK version 2.6.3 for corral
// via /usr/local/bin/sesl ../testcases/svcomp/memsafety/test-0158-2.i -ll ../testcases/svcomp/memsafety/test-0158-2_IR.ll --bpl ../testcases/svcomp/memsafety/test-0158-2.bpl -t --sh-mem-leak --add-line-info

const {:global_variable} {:pointer_to_size 16} .str: ref;
axiom (.str == $sub.ref(0, 1026));
const {:global_variable} {:pointer_to_size 112} {:count 14} .str.1: ref;
axiom (.str.1 == $sub.ref(0, 2064));
const {:global_variable} {:pointer_to_size 152} {:count 19} __PRETTY_FUNCTION__.reach_error: ref;
axiom (__PRETTY_FUNCTION__.reach_error == $sub.ref(0, 3107));
const reach_error: ref;
axiom (reach_error == $sub.ref(0, 4139));
procedure  reach_error()
{
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-2.i", 12, 83} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-2.i", 12, 83} true;
  call __assert_fail(.str, .str.1, 3, __PRETTY_FUNCTION__.reach_error);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-2.i", 12, 83} true;
  assume false;
}
const __assert_fail: ref;
axiom (__assert_fail == $sub.ref(0, 5171));
procedure  __assert_fail($p0: ref, $p1: ref, $i2: i32, $p3: ref);
const main: ref;
axiom (main == $sub.ref(0, 6203));
procedure {:entrypoint} main()
  returns ($r: i32)
{
  var $p0: ref;
  var $p1: ref8;
  var $p2: ref;
  var $p3: ref8;
  var $p4: ref;
  var $p5: ref;
  var $p6: ref;
  var $p7: ref;
  var $p8: ref8;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-2.i", 533, 15} true;
  call {:cexpr "smack:entry:main"} boogie_si_record_ref(main);
  call $p0 := $alloc($mul.ref(24, $zext.i32.i64(1)));
  assume true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-2.i", 533, 15} true;
  call $p1 := malloc(37);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-2.i", 533, 10} true;
  $p2 := $bitcast.ref.ref($p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-2.i", 533, 13} true;
  $M.0 := $store.ref($M.0, $p2, $p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-2.i", 534, 19} true;
  $p3 := $bitcast.ref.ref($p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-2.i", 534, 10} true;
  $p4 := $bitcast.ref.ref($p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-2.i", 534, 14} true;
  $p5 := $add.ref($add.ref($p4, $mul.ref(0, 24)), $mul.ref(16, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-2.i", 534, 17} true;
  $M.1 := $store.ref($M.1, $p5, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-2.i", 535, 10} true;
  $p6 := $bitcast.ref.ref($p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-2.i", 535, 14} true;
  $p7 := $add.ref($add.ref($p6, $mul.ref(0, 24)), $mul.ref(0, 1));
  $p8 := $add.ref($add.ref($add.ref($p6, $mul.ref(0, 24)), $mul.ref(0, 1)), $mul.ref(1, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-2.i", 535, 19} true;
  $M.0 := $store.i8($M.0, $p8, 8);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-2.i", 536, 5} true;
  $r := 0;
  return;
}
const llvm.dbg.declare: ref;
axiom (llvm.dbg.declare == $sub.ref(0, 7235));
procedure  llvm.dbg.declare($p0: ref, $p1: ref, $p2: ref);
const malloc: ref;
axiom (malloc == $sub.ref(0, 8267));
procedure  malloc($i0: i32)
  returns ($r: ref)
{
  call $r := $malloc($zext.i32.i64($i0));
}
const __SMACK_static_init: ref;
axiom (__SMACK_static_init == $sub.ref(0, 9299));
procedure  __SMACK_static_init()
{
$bb0:
  return;
}
procedure  boogie_si_record_ref(x: ref);
procedure  $initialize()
{
  call __SMACK_static_init();
  return;
}
