// generated by SMACK version 2.6.3 for corral
// via /usr/local/bin/smack ../testcases/svcomp/memsafety/test-0219.i -ll ../testcases/svcomp/memsafety/test-0219_IR.ll --bpl ../testcases/svcomp/memsafety/test-0219.bpl -t --sh-mem-leak --add-line-info

const {:global_variable} {:pointer_to_size 16} .str: ref;
axiom (.str == $sub.ref(0, 1026));
const {:global_variable} {:pointer_to_size 96} {:count 12} .str.1: ref;
axiom (.str.1 == $sub.ref(0, 2062));
const {:global_variable} {:pointer_to_size 152} {:count 19} __PRETTY_FUNCTION__.reach_error: ref;
axiom (__PRETTY_FUNCTION__.reach_error == $sub.ref(0, 3105));
const {:global_variable} {:pointer_to_size 64} main.list: ref;
axiom (main.list == $sub.ref(0, 4137));
const reach_error: ref;
axiom (reach_error == $sub.ref(0, 5169));
procedure  reach_error()
{
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 12, 83} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 12, 83} true;
  call __assert_fail(.str, .str.1, 3, __PRETTY_FUNCTION__.reach_error);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 12, 83} true;
  assume false;
}
const __assert_fail: ref;
axiom (__assert_fail == $sub.ref(0, 6201));
procedure  __assert_fail($p0: ref, $p1: ref, $i2: i32, $p3: ref);
const main: ref;
axiom (main == $sub.ref(0, 7233));
procedure {:entrypoint} main()
  returns ($r: i32)
{
  var $i0: i32;
  var $i1: i1;
  var $p2: ref;
  var $p3: ref;
  var $p4: ref;
  var $p5: ref;
  var $p6: ref;
  var $p7: ref;
  var $p8: ref;
  var $p9: ref8;
  var $p10: ref;
  var $i11: i1;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 688, 5} true;
  call {:cexpr "smack:entry:main"} boogie_si_record_ref(main);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 688, 5} true;
  goto $bb1;
$bb1:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 689, 9} true;
  call l1_insert(main.list);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 689, 9} true;
  goto $bb2;
$bb2:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 690, 12} true;
  call $i0 := __VERIFIER_nondet_int();
  call {:cexpr "smack:ext:__VERIFIER_nondet_int"} boogie_si_record_i32($i0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 689, 9} true;
  $i1 := $ne.i32($i0, 0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 689, 9} true;
  assume {:branchcond $i1} true;
  goto $bb3, $bb4;
$bb3:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 689, 9} true;
  assume ($i1 == 1);
  goto $bb1;
$bb4:
  assume !(($i1 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 691, 5} true;
  goto $bb5;
$bb5:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 692, 27} true;
  $p2 := $load.ref($M.0, main.list);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 692, 33} true;
  $p3 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 692, 33} true;
  $p4 := $load.ref($M.1, $p3);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 693, 20} true;
  $p5 := $load.ref($M.0, main.list);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 693, 26} true;
  $p6 := $add.ref($add.ref($p5, $mul.ref(0, 16)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 693, 26} true;
  $p7 := $load.ref($M.1, $p6);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 693, 9} true;
  call l2_destroy($p7);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 694, 14} true;
  $p8 := $load.ref($M.0, main.list);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 694, 14} true;
  $p9 := $bitcast.ref.ref($p8);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 694, 9} true;
  call free_($p9);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 695, 14} true;
  $M.0 := $store.ref($M.0, main.list, $p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 696, 5} true;
  goto $bb6;
$bb6:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 697, 12} true;
  $p10 := $load.ref($M.0, main.list);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 696, 5} true;
  $i11 := $ne.ref($p10, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 696, 5} true;
  assume {:branchcond $i11} true;
  goto $bb7, $bb8;
$bb7:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 696, 5} true;
  assume ($i11 == 1);
  goto $bb5;
$bb8:
  assume !(($i11 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 698, 1} true;
  $r := 0;
  return;
}
const l1_insert: ref;
axiom (l1_insert == $sub.ref(0, 8265));
procedure  l1_insert($p0: ref)
{
  var $p1: ref8;
  var $p2: ref;
  var $i3: i1;
  var $p4: ref;
  var $i5: i32;
  var $i6: i1;
  var $p7: ref;
  var $p8: ref;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 676, 23} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 676, 23} true;
  call $p1 := calloc_model(1, 16);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 676, 23} true;
  $p2 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 677, 10} true;
  $i3 := $ne.ref($p2, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 677, 9} true;
  assume {:branchcond $i3} true;
  goto $bb1, $bb2;
$bb1:
  assume ($i3 == 1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 679, 5} true;
  goto $bb3;
$bb2:
  assume !(($i3 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 678, 9} true;
  call abort();
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 678, 9} true;
  assume false;
$bb3:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 680, 26} true;
  $p4 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 680, 9} true;
  call l2_insert($p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 680, 9} true;
  goto $bb4;
$bb4:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 681, 12} true;
  call $i5 := __VERIFIER_nondet_int();
  call {:cexpr "smack:ext:__VERIFIER_nondet_int"} boogie_si_record_i32($i5);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 680, 9} true;
  $i6 := $ne.i32($i5, 0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 680, 9} true;
  assume {:branchcond $i6} true;
  goto $bb5, $bb6;
$bb5:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 680, 9} true;
  assume ($i6 == 1);
  goto $bb3;
$bb6:
  assume !(($i6 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 682, 18} true;
  $p7 := $load.ref($M.0, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 682, 11} true;
  $p8 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 682, 16} true;
  $M.1 := $store.ref($M.1, $p8, $p7);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 683, 11} true;
  $M.0 := $store.ref($M.0, $p0, $p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 684, 1} true;
  return;
}
const __VERIFIER_nondet_int: ref;
axiom (__VERIFIER_nondet_int == $sub.ref(0, 9297));
procedure  __VERIFIER_nondet_int()
  returns ($r: i32);
const llvm.dbg.declare: ref;
axiom (llvm.dbg.declare == $sub.ref(0, 10329));
procedure  llvm.dbg.declare($p0: ref, $p1: ref, $p2: ref);
const l2_destroy: ref;
axiom (l2_destroy == $sub.ref(0, 11361));
procedure  l2_destroy($p0: ref)
{
  var $p1: ref;
  var $p2: ref;
  var $p3: ref;
  var $p4: ref;
  var $p5: ref8;
  var $p6: ref8;
  var $i7: i1;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 666, 5} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 666, 5} true;
  $p1 := $p0;
  goto $bb1;
$bb1:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 667, 33} true;
  $p2 := $add.ref($add.ref($p1, $mul.ref(0, 16)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 667, 33} true;
  $p3 := $load.ref($M.1, $p2);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 668, 20} true;
  $p4 := $add.ref($add.ref($p1, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 668, 20} true;
  $p5 := $load.ref($M.1, $p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 668, 9} true;
  call free_($p5);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 669, 14} true;
  $p6 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 669, 9} true;
  call free_($p6);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 671, 5} true;
  goto $bb2;
$bb2:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 671, 5} true;
  $i7 := $ne.ref($p3, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 671, 5} true;
  assume {:branchcond $i7} true;
  goto $bb3, $bb4;
$bb3:
  assume ($i7 == 1);
  $p1 := $p3;
  goto $bb1;
$bb4:
  assume !(($i7 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 673, 1} true;
  return;
}
const free_: ref;
axiom (free_ == $sub.ref(0, 12393));
procedure  free_($p0: ref)
{
  call $free($p0);
}
const calloc_model: ref;
axiom (calloc_model == $sub.ref(0, 13425));
procedure  calloc_model($i0: i32, $i1: i32)
  returns ($r: ref)
{
  var $i2: i32;
  var $p3: ref8;
  var $i4: i32;
  var $p5: ref8;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 641, 30} true;
  call {:cexpr "calloc_model:arg:nmemb"} boogie_si_record_i32($i0);
  call {:cexpr "calloc_model:arg:size"} boogie_si_record_i32($i1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 641, 30} true;
  $i2 := $mul.i32($i0, $i1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 641, 17} true;
  call $p3 := malloc($i2);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 642, 33} true;
  $i4 := $mul.i32($i0, $i1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 642, 12} true;
  call $p5 := memset($p3, 0, $i4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 642, 5} true;
  $r := $p5;
  return;
}
const abort: ref;
axiom (abort == $sub.ref(0, 14457));
procedure  abort();
const l2_insert: ref;
axiom (l2_insert == $sub.ref(0, 15489));
procedure  l2_insert($p0: ref)
{
  var $p1: ref8;
  var $p2: ref;
  var $i3: i1;
  var $p4: ref8;
  var $p5: ref;
  var $p6: ref;
  var $p7: ref8;
  var $i8: i1;
  var $p9: ref;
  var $p10: ref;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 655, 23} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 655, 23} true;
  call $p1 := calloc_model(1, 16);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 655, 23} true;
  $p2 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 656, 10} true;
  $i3 := $ne.ref($p2, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 656, 9} true;
  assume {:branchcond $i3} true;
  goto $bb1, $bb2;
$bb1:
  assume ($i3 == 1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 658, 19} true;
  call $p4 := malloc(119);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 658, 11} true;
  $p5 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 658, 17} true;
  $M.1 := $store.ref($M.1, $p5, $p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 659, 16} true;
  $p6 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 659, 16} true;
  $p7 := $load.ref($M.1, $p6);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 659, 10} true;
  $i8 := $ne.ref($p7, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 659, 9} true;
  assume {:branchcond $i8} true;
  goto $bb3, $bb4;
$bb2:
  assume !(($i3 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 657, 9} true;
  call abort();
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 657, 9} true;
  assume false;
$bb3:
  assume ($i8 == 1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 661, 18} true;
  $p9 := $load.ref($M.1, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 661, 11} true;
  $p10 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 661, 16} true;
  $M.1 := $store.ref($M.1, $p10, $p9);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 662, 11} true;
  $M.1 := $store.ref($M.1, $p0, $p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 663, 1} true;
  return;
$bb4:
  assume !(($i8 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 660, 9} true;
  call abort();
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.i", 660, 9} true;
  assume false;
}
const malloc: ref;
axiom (malloc == $sub.ref(0, 16521));
procedure  malloc($i0: i32)
  returns ($r: ref)
{
  call $r := $malloc($zext.i32.i64($i0));
}
const memset: ref;
axiom (memset == $sub.ref(0, 17553));
procedure  memset($p0: ref, $i1: i32, $i2: i32)
  returns ($r: ref);
const llvm.dbg.value: ref;
axiom (llvm.dbg.value == $sub.ref(0, 18585));
procedure  llvm.dbg.value($p0: ref, $p1: ref, $p2: ref);
const __SMACK_static_init: ref;
axiom (__SMACK_static_init == $sub.ref(0, 19617));
procedure  __SMACK_static_init()
{
$bb0:
  $M.0 := $store.ref($M.0, main.list, $0.ref);
  return;
}
procedure  boogie_si_record_i32(x: i32);
procedure  boogie_si_record_ref(x: ref);
procedure  $initialize()
{
  call __SMACK_static_init();
  return;
}
