// generated by SMACK version 2.6.3 for corral
// via /usr/local/bin/smack svcomp/memsafety/test-0158-1.c -ll svcomp/memsafety/test-0158-1_IR.ll --bpl svcomp/memsafety/test-0158-1.bpl -t --sh-mem-leak

const {:global_variable} {:pointer_to_size 16} .str: ref;
axiom (.str == $sub.ref(0, 1026));
const {:global_variable} {:pointer_to_size 248} {:count 31} .str.1: ref;
axiom (.str.1 == $sub.ref(0, 2081));
const {:global_variable} {:pointer_to_size 152} {:count 19} __PRETTY_FUNCTION__.reach_error: ref;
axiom (__PRETTY_FUNCTION__.reach_error == $sub.ref(0, 3124));
const reach_error: ref;
axiom (reach_error == $sub.ref(0, 4156));
procedure  reach_error()
{
$bb0:
  call __assert_fail(.str, .str.1, 3, __PRETTY_FUNCTION__.reach_error);
  assume false;
}
const __assert_fail: ref;
axiom (__assert_fail == $sub.ref(0, 5188));
procedure  __assert_fail($p0: ref, $p1: ref, $i2: i32, $p3: ref);
const main: ref;
axiom (main == $sub.ref(0, 6220));
procedure {:entrypoint} main()
  returns ($r: i32)
{
  var $p0: ref;
  var $p1: ref8;
  var $p2: ref;
  var $p3: ref8;
  var $p4: ref;
  var $p5: ref;
  var $p6: ref;
  var $p7: ref8;
$bb0:
  call {:cexpr "smack:entry:main"} boogie_si_record_ref(main);
  call $p0 := $alloc($mul.ref(24, $zext.i32.i64(1)));
  assume true;
  call $p1 := malloc(37);
  $p2 := $bitcast.ref.ref($p0);
  $M.0 := $store.ref($M.0, $p2, $p1);
  $p3 := $bitcast.ref.ref($p0);
  $p4 := $bitcast.ref.ref($p0);
  $p5 := $add.ref($add.ref($p4, $mul.ref(0, 24)), $mul.ref(16, 1));
  $M.1 := $store.ref($M.1, $p5, $p0);
  $p6 := $bitcast.ref.ref($p0);
  $p7 := $load.ref($M.0, $p6);
  call free_($p7);
  $r := 0;
  return;
}
const llvm.dbg.declare: ref;
axiom (llvm.dbg.declare == $sub.ref(0, 7252));
procedure  llvm.dbg.declare($p0: ref, $p1: ref, $p2: ref);
const malloc: ref;
axiom (malloc == $sub.ref(0, 8284));
procedure  malloc($i0: i64)
  returns ($r: ref)
{
  call $r := $malloc($i0);
}
const free_: ref;
axiom (free_ == $sub.ref(0, 9316));
procedure  free_($p0: ref)
{
  call $free($p0);
}
const __SMACK_static_init: ref;
axiom (__SMACK_static_init == $sub.ref(0, 10348));
procedure  __SMACK_static_init()
{
$bb0:
  return;
}
procedure  boogie_si_record_ref(x: ref);
procedure  $initialize()
{
  call __SMACK_static_init();
  return;
}
