// generated by SMACK version 2.6.3 for corral
// via /usr/local/bin/smack ../testcases/svcomp/memsafety/test-0158-3.c -ll ../testcases/svcomp/memsafety/test-0158-3_IR.ll --bpl ../testcases/svcomp/memsafety/test-0158-3.bpl -t --sh-mem-leak --add-line-info

const {:global_variable} {:pointer_to_size 16} .str: ref;
axiom (.str == $sub.ref(0, 1026));
const {:global_variable} {:pointer_to_size 352} {:count 44} .str.1: ref;
axiom (.str.1 == $sub.ref(0, 2094));
const {:global_variable} {:pointer_to_size 152} {:count 19} __PRETTY_FUNCTION__.reach_error: ref;
axiom (__PRETTY_FUNCTION__.reach_error == $sub.ref(0, 3137));
const reach_error: ref;
axiom (reach_error == $sub.ref(0, 4169));
procedure  reach_error()
{
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 3, 22} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 3, 22} true;
  call __assert_fail(.str, .str.1, 3, __PRETTY_FUNCTION__.reach_error);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 3, 22} true;
  assume false;
}
const __assert_fail: ref;
axiom (__assert_fail == $sub.ref(0, 5201));
procedure  __assert_fail($p0: ref, $p1: ref, $i2: i32, $p3: ref);
const main: ref;
axiom (main == $sub.ref(0, 6233));
procedure {:entrypoint} main()
  returns ($r: i32)
{
  var $p0: ref;
  var $p1: ref8;
  var $p2: ref;
  var $p3: ref8;
  var $p4: ref;
  var $p5: ref;
  var $p6: ref;
  var $p7: ref8;
  var $p8: ref;
  var $p9: ref;
  var $p10: ref8;
  var $p11: ref;
  var $p12: ref8;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 22, 15} true;
  call {:cexpr "smack:entry:main"} boogie_si_record_ref(main);
  call $p0 := $alloc($mul.ref(24, $zext.i32.i64(1)));
  assume true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 22, 15} true;
  call $p1 := malloc(37);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 22, 10} true;
  $p2 := $bitcast.ref.ref($p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 22, 13} true;
  $M.0 := $store.ref($M.0, $p2, $p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 25, 19} true;
  $p3 := $bitcast.ref.ref($p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 25, 10} true;
  $p4 := $bitcast.ref.ref($p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 25, 14} true;
  $p5 := $add.ref($add.ref($p4, $mul.ref(0, 24)), $mul.ref(16, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 25, 17} true;
  $M.1 := $store.ref($M.1, $p5, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 28, 22} true;
  $p6 := $bitcast.ref.ref($p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 28, 22} true;
  $p7 := $load.ref($M.0, $p6);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 31, 10} true;
  $p8 := $bitcast.ref.ref($p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 31, 14} true;
  $p9 := $add.ref($add.ref($p8, $mul.ref(0, 24)), $mul.ref(0, 1));
  $p10 := $add.ref($add.ref($add.ref($p8, $mul.ref(0, 24)), $mul.ref(0, 1)), $mul.ref(1, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 31, 19} true;
  $M.0 := $store.i8($M.0, $p10, 8);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 32, 15} true;
  $p11 := $bitcast.ref.ref($p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 32, 15} true;
  $p12 := $load.ref($M.0, $p11);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 32, 5} true;
  call free_($p12);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 34, 5} true;
  call free_($p7);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0158-3.c", 35, 5} true;
  $r := 0;
  return;
}
const llvm.dbg.declare: ref;
axiom (llvm.dbg.declare == $sub.ref(0, 7265));
procedure  llvm.dbg.declare($p0: ref, $p1: ref, $p2: ref);
const malloc: ref;
axiom (malloc == $sub.ref(0, 8297));
procedure  malloc($i0: i64)
  returns ($r: ref)
{
  call $r := $malloc($i0);
}
const free_: ref;
axiom (free_ == $sub.ref(0, 9329));
procedure  free_($p0: ref)
{
  call $free($p0);
}
const llvm.dbg.value: ref;
axiom (llvm.dbg.value == $sub.ref(0, 10361));
procedure  llvm.dbg.value($p0: ref, $p1: ref, $p2: ref);
const __SMACK_static_init: ref;
axiom (__SMACK_static_init == $sub.ref(0, 11393));
procedure  __SMACK_static_init()
{
$bb0:
  return;
}
procedure  boogie_si_record_ref(x: ref);
procedure  $initialize()
{
  call __SMACK_static_init();
  return;
}
