// generated by SMACK version 2.6.3 for corral
// via /usr/local/bin/smack ../testcases/svcomp/memsafety/test-0219.c -ll ../testcases/svcomp/memsafety/test-0219_IR.ll --bpl ../testcases/svcomp/memsafety/test-0219.bpl -t --sh-mem-leak --add-line-info

const {:global_variable} {:pointer_to_size 16} .str: ref;
axiom (.str == $sub.ref(0, 1026));
const {:global_variable} {:pointer_to_size 336} {:count 42} .str.1: ref;
axiom (.str.1 == $sub.ref(0, 2092));
const {:global_variable} {:pointer_to_size 152} {:count 19} __PRETTY_FUNCTION__.reach_error: ref;
axiom (__PRETTY_FUNCTION__.reach_error == $sub.ref(0, 3135));
const {:global_variable} {:pointer_to_size 64} main.list: ref;
axiom (main.list == $sub.ref(0, 4167));
const reach_error: ref;
axiom (reach_error == $sub.ref(0, 5199));
procedure  reach_error()
{
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 3, 22} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 3, 22} true;
  call __assert_fail(.str, .str.1, 3, __PRETTY_FUNCTION__.reach_error);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 3, 22} true;
  assume false;
}
const __assert_fail: ref;
axiom (__assert_fail == $sub.ref(0, 6231));
procedure  __assert_fail($p0: ref, $p1: ref, $i2: i32, $p3: ref);
const main: ref;
axiom (main == $sub.ref(0, 7263));
procedure {:entrypoint} main()
  returns ($r: i32)
{
  var $i0: i32;
  var $i1: i1;
  var $p2: ref;
  var $p3: ref;
  var $p4: ref;
  var $p5: ref;
  var $p6: ref;
  var $p7: ref;
  var $p8: ref;
  var $p9: ref8;
  var $p10: ref;
  var $i11: i1;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 68, 5} true;
  call {:cexpr "smack:entry:main"} boogie_si_record_ref(main);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 68, 5} true;
  goto $bb1;
$bb1:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 69, 9} true;
  call l1_insert(main.list);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 69, 9} true;
  goto $bb2;
$bb2:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 70, 12} true;
  call $i0 := __VERIFIER_nondet_int();
  call {:cexpr "smack:ext:__VERIFIER_nondet_int"} boogie_si_record_i32($i0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 69, 9} true;
  $i1 := $ne.i32($i0, 0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 69, 9} true;
  assume {:branchcond $i1} true;
  goto $bb3, $bb4;
$bb3:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 69, 9} true;
  assume ($i1 == 1);
  goto $bb1;
$bb4:
  assume !(($i1 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 72, 5} true;
  goto $bb5;
$bb5:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 73, 27} true;
  $p2 := $load.ref($M.0, main.list);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 73, 33} true;
  $p3 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 73, 33} true;
  $p4 := $load.ref($M.1, $p3);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 75, 20} true;
  $p5 := $load.ref($M.0, main.list);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 75, 26} true;
  $p6 := $add.ref($add.ref($p5, $mul.ref(0, 16)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 75, 26} true;
  $p7 := $load.ref($M.1, $p6);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 75, 9} true;
  call l2_destroy($p7);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 77, 14} true;
  $p8 := $load.ref($M.0, main.list);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 77, 14} true;
  $p9 := $bitcast.ref.ref($p8);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 77, 9} true;
  call free_($p9);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 78, 14} true;
  $M.0 := $store.ref($M.0, main.list, $p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 79, 5} true;
  goto $bb6;
$bb6:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 80, 12} true;
  $p10 := $load.ref($M.0, main.list);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 79, 5} true;
  $i11 := $ne.ref($p10, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 79, 5} true;
  assume {:branchcond $i11} true;
  goto $bb7, $bb8;
$bb7:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 79, 5} true;
  assume ($i11 == 1);
  goto $bb5;
$bb8:
  assume !(($i11 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 81, 1} true;
  $r := 0;
  return;
}
const l1_insert: ref;
axiom (l1_insert == $sub.ref(0, 8295));
procedure  l1_insert($p0: ref)
{
  var $p1: ref8;
  var $p2: ref;
  var $i3: i1;
  var $p4: ref;
  var $i5: i32;
  var $i6: i1;
  var $p7: ref;
  var $p8: ref;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 52, 23} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 52, 23} true;
  call $p1 := calloc_model(1, 16);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 52, 23} true;
  $p2 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 53, 10} true;
  $i3 := $ne.ref($p2, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 53, 9} true;
  assume {:branchcond $i3} true;
  goto $bb1, $bb2;
$bb1:
  assume ($i3 == 1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 56, 5} true;
  goto $bb3;
$bb2:
  assume !(($i3 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 54, 9} true;
  call abort();
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 54, 9} true;
  assume false;
$bb3:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 57, 26} true;
  $p4 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 57, 9} true;
  call l2_insert($p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 57, 9} true;
  goto $bb4;
$bb4:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 58, 12} true;
  call $i5 := __VERIFIER_nondet_int();
  call {:cexpr "smack:ext:__VERIFIER_nondet_int"} boogie_si_record_i32($i5);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 57, 9} true;
  $i6 := $ne.i32($i5, 0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 57, 9} true;
  assume {:branchcond $i6} true;
  goto $bb5, $bb6;
$bb5:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 57, 9} true;
  assume ($i6 == 1);
  goto $bb3;
$bb6:
  assume !(($i6 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 60, 18} true;
  $p7 := $load.ref($M.0, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 60, 11} true;
  $p8 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 60, 16} true;
  $M.1 := $store.ref($M.1, $p8, $p7);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 61, 11} true;
  $M.0 := $store.ref($M.0, $p0, $p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 62, 1} true;
  return;
}
const __VERIFIER_nondet_int: ref;
axiom (__VERIFIER_nondet_int == $sub.ref(0, 9327));
procedure  __VERIFIER_nondet_int()
  returns ($r: i32);
const llvm.dbg.declare: ref;
axiom (llvm.dbg.declare == $sub.ref(0, 10359));
procedure  llvm.dbg.declare($p0: ref, $p1: ref, $p2: ref);
const l2_destroy: ref;
axiom (l2_destroy == $sub.ref(0, 11391));
procedure  l2_destroy($p0: ref)
{
  var $p1: ref;
  var $p2: ref;
  var $p3: ref;
  var $p4: ref;
  var $p5: ref8;
  var $p6: ref8;
  var $i7: i1;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 41, 5} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 41, 5} true;
  $p1 := $p0;
  goto $bb1;
$bb1:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 42, 33} true;
  $p2 := $add.ref($add.ref($p1, $mul.ref(0, 16)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 42, 33} true;
  $p3 := $load.ref($M.1, $p2);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 43, 20} true;
  $p4 := $add.ref($add.ref($p1, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 43, 20} true;
  $p5 := $load.ref($M.1, $p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 43, 9} true;
  call free_($p5);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 44, 14} true;
  $p6 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 44, 9} true;
  call free_($p6);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 46, 5} true;
  goto $bb2;
$bb2:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 46, 5} true;
  $i7 := $ne.ref($p3, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 46, 5} true;
  assume {:branchcond $i7} true;
  goto $bb3, $bb4;
$bb3:
  assume ($i7 == 1);
  $p1 := $p3;
  goto $bb1;
$bb4:
  assume !(($i7 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 48, 1} true;
  return;
}
const free_: ref;
axiom (free_ == $sub.ref(0, 12423));
procedure  free_($p0: ref)
{
  call $free($p0);
}
const calloc_model: ref;
axiom (calloc_model == $sub.ref(0, 13455));
procedure  calloc_model($i0: i64, $i1: i64)
  returns ($r: ref)
{
  var $i2: i64;
  var $p3: ref8;
  var $i4: i64;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 9, 30} true;
  call {:cexpr "calloc_model:arg:nmemb"} boogie_si_record_i64($i0);
  call {:cexpr "calloc_model:arg:size"} boogie_si_record_i64($i1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 9, 30} true;
  $i2 := $mul.i64($i0, $i1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 9, 17} true;
  call $p3 := malloc($i2);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 10, 33} true;
  $i4 := $mul.i64($i0, $i1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 10, 12} true;
  call $M.1 := $memset.i8($M.1, $p3, 0, $i4, false);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 10, 5} true;
  $r := $p3;
  return;
}
const abort: ref;
axiom (abort == $sub.ref(0, 14487));
procedure  abort();
const l2_insert: ref;
axiom (l2_insert == $sub.ref(0, 15519));
procedure  l2_insert($p0: ref)
{
  var $p1: ref8;
  var $p2: ref;
  var $i3: i1;
  var $p4: ref8;
  var $p5: ref;
  var $p6: ref;
  var $p7: ref8;
  var $i8: i1;
  var $p9: ref;
  var $p10: ref;
$bb0:
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 27, 23} true;
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 27, 23} true;
  call $p1 := calloc_model(1, 16);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 27, 23} true;
  $p2 := $bitcast.ref.ref($p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 28, 10} true;
  $i3 := $ne.ref($p2, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 28, 9} true;
  assume {:branchcond $i3} true;
  goto $bb1, $bb2;
$bb1:
  assume ($i3 == 1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 31, 19} true;
  call $p4 := malloc(119);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 31, 11} true;
  $p5 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 31, 17} true;
  $M.1 := $store.ref($M.1, $p5, $p4);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 32, 16} true;
  $p6 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(0, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 32, 16} true;
  $p7 := $load.ref($M.1, $p6);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 32, 10} true;
  $i8 := $ne.ref($p7, $0.ref);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 32, 9} true;
  assume {:branchcond $i8} true;
  goto $bb3, $bb4;
$bb2:
  assume !(($i3 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 29, 9} true;
  call abort();
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 29, 9} true;
  assume false;
$bb3:
  assume ($i8 == 1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 35, 18} true;
  $p9 := $load.ref($M.1, $p0);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 35, 11} true;
  $p10 := $add.ref($add.ref($p2, $mul.ref(0, 16)), $mul.ref(8, 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 35, 16} true;
  $M.1 := $store.ref($M.1, $p10, $p9);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 36, 11} true;
  $M.1 := $store.ref($M.1, $p0, $p1);
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 37, 1} true;
  return;
$bb4:
  assume !(($i8 == 1));
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 33, 9} true;
  call abort();
  assume {:sourceloc "../testcases/svcomp/memsafety/test-0219.c", 33, 9} true;
  assume false;
}
const malloc: ref;
axiom (malloc == $sub.ref(0, 16551));
procedure  malloc($i0: i64)
  returns ($r: ref)
{
  call $r := $malloc($i0);
}
const llvm.memset.p0i8.i64: ref;
axiom (llvm.memset.p0i8.i64 == $sub.ref(0, 17583));
procedure  llvm.memset.p0i8.i64($p0: ref, $i1: i8, $i2: i64, $i3: i1);
const llvm.dbg.value: ref;
axiom (llvm.dbg.value == $sub.ref(0, 18615));
procedure  llvm.dbg.value($p0: ref, $p1: ref, $p2: ref);
const __SMACK_static_init: ref;
axiom (__SMACK_static_init == $sub.ref(0, 19647));
procedure  __SMACK_static_init()
{
$bb0:
  $M.0 := $store.ref($M.0, main.list, $0.ref);
  return;
}
procedure  $memset.i8(M: [ref] i8, dst: ref, val: i8, len: ref, isvolatile: bool) returns (M.ret: [ref] i8)
{
  assume (forall x: ref :: $sle.ref.bool(dst,x) && $slt.ref.bool(x,$add.ref(dst,len)) ==> M.ret[x] == val);
  assume (forall x: ref :: $slt.ref.bool(x,dst) ==> M.ret[x] == M[x]);
  assume (forall x: ref :: $sle.ref.bool($add.ref(dst,len),x) ==> M.ret[x] == M[x]);
}

procedure  boogie_si_record_i32(x: i32);
procedure  boogie_si_record_i64(x: i64);
procedure  boogie_si_record_ref(x: ref);
procedure  $initialize()
{
  call __SMACK_static_init();
  return;
}
