language: cpp
cache: apt
env:
  matrix:
     - os: linux
       dist: trusty
       language: generic
services:
  - docker

install: true

script:
  ### build with docker
  - docker build -t seahorn/sea-dsa-builder:bionic-llvm10 -f docker/sea-dsa-builder.Dockerfile .

notifications:
   slack: seahornteam:NAUqZmZHFFviPH4ktQbJXgKu
   email:
     recipients:
      - seahorn-build@googlegroups.com
     on_success: always
     on_failure: always

